### PR TITLE
Add basic 3D mouse support

### LINKED ISSUE #26: 3D mouse support
Please implement support for 3DConnexion input devices.

On Linux, [libspnav](https://github.com/FreeSpacenav/libspnav) can talk to spacenavd.  I am not super familiar with the official 3DxWare SDK on other platforms, but it would provide similar functionality.  An important note, 3DConnexion themselves [contributed the SDK to KiCAD](https://gitlab.com/kicad/code/kicad/-/tree/master/thirdparty/3dxware_sdk) under the GPLv3 so it should be completely compatible to include.

### PR DESCRIPTION
**Pull request by jue89**
This is my attempt to introduce spnav support by copying the Horizon EDA implementation.

ToDos:

- [x] add support for rotation
- [x] replace magic numbers with `const`s

Closes #26

### CODE REVIEW

**Comment by carrotIndustries** [comment]
For rotation, you should be able to copy/paste from there: https://github.com/dune3d/dune3d/blob/766aebba96df3440a0cb685d01c174f65656d799/src/canvas/canvas.cpp#L286

**Comment by jue89** [comment]
Thank you! I was scared by the quaternions magic :-D (Haven't understood them, yet. Tried that in university and failed ;-))

**Comment by jue89** [comment]
Well I think the basic functionality is implemented. I've tried to copy the behavior of FreeCAD which feels natural to me.

**Comment by jue89** [comment]
I decided to rely on the `spnavcfg` tool for configuration of the sensitivity of the 3D mouse and used hard-coded scaling.

I think this is ready for review ;-)

**Comment by carrotIndustries** [comment]
See https://github.com/dune3d/dune3d/tree/spnav for the changes I did to the code to make the navigation more intuitive (at least for my type of spacemouse). Let me know if you think the same.

**Comment by jue89** [comment]
TBH - I can't use it anymore :D

What kind of spacemouse do you own?

I was able to make it usable by applying these settings:

Screenshot from 2024-01-07 19-07-53

Why have you removed the slow-down of ration speed when the camera is zoomed in?

**Comment by carrotIndustries** [comment]
> What kind of spacemouse do you own?

A really old one: http://spacemice.org/index.php?title=Spacemouse_Classic

> Why have you removed the slow-down of ration speed when the camera is zoomed in?

The idea is that the knob on the mouse corresponds to the object in 3D space, so rotation should always have the same effect. Might be personal preference tough.

**Comment by jue89** [comment]
> > Why have you removed the slow-down of ration speed when the camera is zoomed in?
> 
> The idea is that the knob on the mouse corresponds to the object in 3D space, so rotation should always have the same effect. Might be personal preference tough.

Yeah, but now if you're pretty close to the object, translation is slowed down and, thus, rotation feels super fast. With my mouse it's hard to navigate in this situation.

**Comment by jue89** [comment]
But aside from that: I like the way you fixed the ration movement! Feels great (with the swapped and inverted axis as shown in the screenshot of the config dialog).

**Comment by carrotIndustries** [comment]
> Yeah, but now if you're pretty close to the object, translation is slowed down and, thus, rotation feels super fast. With my mouse it's hard to navigate in this situation.

Doesn't this more depend on the distance between screen center and rotation center point? Looking at a model that sits at the origin, with the camera looking at the origin it shouldn't make a difference if the model is 1mm in size and the camera is 2mm away from it or the model is 1m in size and the camera is 2m away from it.

**Comment by jue89** [comment]
Okay, I won't block this PR because of that and can life with your patch when I swap and invert the mentioned axis ;-)

I guess it's the driver assigning weird axis the my space mouse. BTW it's a *3Dconnexion SpaceMouse Compact*.

Should I updated this PR? Or do you just use your branch?

**Comment by jue89** [comment]
> > Should I updated this PR? Or do you just use your branch?
> 
> If you're okay with it, I'd use my branch.

Sure :-)

**Comment by carrotIndustries** [comment]
I just upgraded my spacenavd to the latest version and found out that this had shuffled the axis. With 3ff37812cdb58de4eba995e75d59777280ab1524 everything is back in order. Can you confirm that this patch works for you as well?

**Comment by jue89** [comment]
> I just upgraded my spacenavd to the latest version and found out that this had shuffled the axis. With [3ff3781](https://github.com/dune3d/dune3d/commit/3ff37812cdb58de4eba995e75d59777280ab1524) everything is back in order. Can you confirm that this patch works for you as well?

Yes! Feels great with default settings for spacenavd.

**Pull request closed without merging**
